---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-us
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
      region: us
  template:
    metadata:
      annotations:
        multicluster.admiralty.io/elect: ""
      labels:
        app: hello-world
        region: us
    spec:
      nodeSelector:
        topology.kubernetes.io/region: us
      containers:
        - image: adamgolab/hello-world
          name: hello-world
          env:
            - name: PORT
              value: "80"
            - name: WORLD
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-eu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
      region: eu
  template:
    metadata:
      annotations:
        multicluster.admiralty.io/elect: ""
      labels:
        app: hello-world
        region: eu
    spec:
      nodeSelector:
        topology.kubernetes.io/region: eu
      containers:
        - image: adamgolab/hello-world
          name: hello-world
          env:
            - name: PORT
              value: "80"
            - name: WORLD
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-world
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: hello-world.user-h9lf2.admiralty.cloud
      http:
        paths:
          - path: /*
            backend:
              serviceName: hello-world
              servicePort: 80
